#################################################################################
# Pipeline triggered on every pull request to run unit and integration tests
#################################################################################
name: Test
env:
  RUST_BACKTRACE: "1"
on:
  merge_group:
    types: [checks_requested]
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
concurrency:
  group: ${{ github.event.pull_request.head.ref || github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  tests-unit:
    name: Unit Tests
    runs-on: self-hosted-hoprnet-bigger
    timeout-minutes: 30
    env:
      CI: "true"
    steps:
      - name: Run unit tests
        uses: hoprnet/hopr-workflows/actions/nix-action@nix-action-v1
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          command: nix develop -c cargo test --lib --all-features

# tests-integration:
#   name: Integration Tests
#   runs-on: ubuntu-latest
#   timeout-minutes: 30
#   env:
#     CI: "true"
#   steps:
#     - name: Run integration tests
#       uses: hoprnet/hopr-workflows/actions/nix-action@nix-action-v1
#       with:
#         repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
#         ref: ${{ github.event.pull_request.head.ref || github.ref }}
#         github_access_token: ${{ secrets.GITHUB_TOKEN }}
#         command: nix develop -c cargo test --test '*' -- --test-threads=1
